version: "3.7"

services:
    flask:
        build: ./app
        image: face-login:1.0
        ports:
            - 5000:5000

    # RUN: docker-compose up tests
    tests:
        image: face-login:1.0
        command: python -m unittest discover -v -s tests -p *.py
